[package]
name = "tablejohn"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
askama = { version = "0.12.0", features = ["with-axum"] }
askama_axum = "0.3.0"
axum = { version = "0.6.19", features = ["macros"] }
clap = { version = "4.3.19", features = ["derive", "deprecated"] }
directories = "5.0.1"
futures = "0.3.28"
humantime = "2.1.0"
humantime-serde = "1.1.1"
mime_guess = "2.0.4"
rust-embed = "6.8.1"
serde = { version = "1.0.181", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio", "sqlite", "time"] }
time = { version = "0.3.25", features = ["formatting", "macros", "parsing"] }
tokio = { version = "1.29.1", features = ["full"] }
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dependencies.gix]
version = "0.51.0"
default-features = false
features = ["max-performance-safe", "extras"]

[build-dependencies]
vergen = { version = "8.2.4", features = ["git", "gitcl"] }
walkdir = "2.3.3"

[profile.dev.package.sqlx-macros]
opt-level = 3
