[package]
name = "tablejohn"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
askama = { version = "0.12.0", features = ["with-axum"] }
askama_axum = "0.3.0"
axum = { version = "0.6.19", features = ["macros"] }
mime_guess = "2.0.4"
rust-embed = "6.8.1"
tokio = { version = "1.29.1", features = ["full"] }
