#!/usr/bin/env bash
curl 'https://raw.githubusercontent.com/leeoniya/uPlot/master/dist/uPlot.d.ts' -o scripts/uPlot.d.ts
curl 'https://raw.githubusercontent.com/leeoniya/uPlot/master/dist/uPlot.esm.js' -o scripts/uPlot.js
curl 'https://raw.githubusercontent.com/leeoniya/uPlot/master/dist/uPlot.min.css' -o static/uPlot.css
sed -i 's/^export = uPlot;$/export { uPlot as default };/' scripts/uPlot.d.ts
